# Generated by Django 6.0 on 2026-01-29 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_username_item'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
